package at.pria.joust.webapp.config

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SecurityInitializer extends AbstractSecurityWebApplicationInitializer
